services:
  gleebai:
    image: ghcr.io/bruglet/gleeb-ai:latest
    container_name: gleebai
    restart: always
    volumes:
      - gleebai-config:/app/config
      # Optional: Use if you want to inspect downloaded files before they are deleted
      - gleebai-temp:/app/temp
    # Change these to your actual tokens. Don't publish these publically!
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

volumes:
  gleebai-config:
  gleebai-temp:
